project_name='NAME'
flags_file='flags.txt'
root_files=[
    'scope.txt',
    'all-creds.txt'
]

[resources]  # Resources links (keep a record of where to check when stuck and useful tools)
links=[
    'https://www.revshells.com/'
]

[host-setup]  # Setup per host (all files to create and more)
files=[
    'writeup.md',
    'data/info/creds.txt',
    'data/raw/cmd.dump',
    'data/raw/netscan.dump',
    'exploits/links.md'
]

# In host names, do not use any other '.' as there are going to be renamed
[standalones]
hosts=['127.0.0.1','127.0.0.2', '127.0.0.6']

[networks]
names=[
    'wan',
    'lan'
]

[networks.wan]
hosts=['127.0.0.1','127.0.0.2']
[networks.lan]
hosts=['127.0.0.1','127.0.0.2']

