[package]
name = "cyber-arsenal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
arg = { version = "0.4.1", features = ["std"] }
chrono = "0.4.38"
clipboard = "0.5.0"
crossterm = "0.27.0"
toml = "0.8.12"
tui = "0.19.0"
